version: '2'
services:

  venv:
    image: python:2.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    environment:
      PYTHONUSERBASE: "/mnt/.python_venv"
    command: pip install -r requirements.txt --upgrade --user

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /mnt
    volumes:
      - .:/mnt
    environment:
      PYTHONUSERBASE: "/mnt/.python_venv"
    extra_hosts:
      - "palvelin:192.168.135.101"